tensorflow/cloud

CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, README.md, tensorflow_cloud/__init__.py, tensorflow_cloud/containerize.py, tensorflow_cloud/deploy.py, tensorflow_cloud/gcp.py, tensorflow_cloud/machine_config.py, tensorflow_cloud/package.py, tensorflow_cloud/preprocess.py, tensorflow_cloud/run.py, tensorflow_cloud/validate.py, tests/call_run_on_script_with_keras_ctl.py, tests/call_run_on_script_with_keras_fit.py, tests/tensorflow_cloud/containerize_test.py, tests/tensorflow_cloud/deploy_test.py, tests/tensorflow_cloud/gcp_test.py, tests/tensorflow_cloud/package_test.py, tests/tensorflow_cloud/preprocess_test.py, tests/tensorflow_cloud/validate_test.py, tests/testdata/mnist_example_using_ctl.py, tests/testdata/mnist_example_using_fit.py, tests/testdata/requirements.txt
Adds `run` API. Adds support for workflow where a python program can be passed as an `entry_point` to `run`.
=> Initial commit.

tensorflow_cloud/containerize.py, tensorflow_cloud/deploy.py, tensorflow_cloud/validate.py, tests/integration/call_run_on_script_with_keras_ctl.py, tests/tensorflow_cloud/deploy_test.py
Adding support for streaming job logs using subprocess and AI platform command.
=> Adding support for streaming logs.

tensorflow_cloud/__init__.py, tensorflow_cloud/containerize.py, tensorflow_cloud/deploy.py, tensorflow_cloud/preprocess.py, tensorflow_cloud/run.py, tests/integration/call_run_on_script_with_keras_ctl.py, tests/integration/call_run_on_script_with_keras_fit.py, tests/integration/call_run_on_script_with_keras_save_and_load.py, tests/integration/call_run_within_script_with_keras_fit.py, tests/testdata/mnist_example_using_ctl.py
Add support using run API in the python script along with the Keras model.
=> Add support using run API in the python script along with the Keras model.

setup.py, tensorflow_cloud/run.py
Update setup with google-cloud-storage dep.
=> Update setup with google-cloud-storage dep.

tensorflow_cloud/deploy.py
Update log streaming function for colab.
=> Update log streaming function for colab.

tensorflow_cloud/containerize.py, tests/tensorflow_cloud/containerize_test.py
Default to py3 for TF docker images.
=> Default to py3 for TF docker images.

tensorflow_cloud/containerize.py
Checking the status ever 30 seconds is still a good idea, so I doubled the number of check cycles to reach 10 mins.
=> Increase default value for max_status_check_attempts

README.md
I'd still like to address the local docker vs cloud bucket issue, but don't want to make any significant changes to the setup structure without your approval.
=> Update setup instructions for ease of use. 

tests/integration/call_run_within_nb_on_colab.ipynb, tests/testdata/keras_tuner_cifar_example.py, tests/testdata/mnist_example_using_fit.ipynb
This PR is to add license header to three files that were missing it. Also removed the execution results from one of the notebooks in the process.
=> Add License to files without a license header

tests/integration/call_run_within_script_with_autokeras_test.py
Adding license header to files with missing license.
=> Add license to file header

tensorflow_cloud/containerize.py
Fix https://github.com/tensorflow/cloud/issues/36
=> Fix RC release image name

README.md, tensorflow_cloud/containerize.py, tensorflow_cloud/run.py
1. Adding flag for checking if running remotely
2. Fix error when trying to string replace '-rc' with 'rc' in version.
3. Add 'py3' tag only for TF docker images < 2.1.0 as the later images are by default py3.
4. Add an error and solution to README section.
=> Adding flag for checking if running remotely, fixing some issues.

.github/workflows/actions.yml
=> Create Github actions YAML file for CI

CODEOWNERS
Similar to TensorFlow repository https://github.com/tensorflow/tensorflow/blob/master/CODEOWNERS
=> Adding CODEOWNERS file.

src/python/tensorflow_cloud/__init__.py
Updating tensorflow_cloud/__init__.py
=> re-order imports and add docstring

src/python/tensorflow_cloud/core/tests/unit/containerize_test.py, src/python/tensorflow_cloud/core/tests/unit/deploy_test.py, src/python/tensorflow_cloud/core/tests/unit/preprocess_test.py, src/python/tensorflow_cloud/core/tests/unit/validate_test.py, src/python/tensorflow_cloud/tuner/optimizer_client.py
=> Remove unit test dependency on absolute path

src/python/tensorflow_cloud/tuner/optimizer_client.py
Add a place holder to allow for injection of additional required test infra specific imports.
=> Add place holder for test infra imports

src/python/tensorflow_cloud/core/containerize.py, src/python/tensorflow_cloud/core/deploy.py, src/python/tensorflow_cloud/core/tests/unit/containerize_test.py, src/python/tensorflow_cloud/core/tests/unit/deploy_test.py, src/python/tensorflow_cloud/core/tests/unit/validate_test.py, src/python/tensorflow_cloud/core/validate.py
- Fixing ambiguous import (whether it's a module vs. function vs. constant). Always import module
- Fixing TensorFlow VERSIONS to be  always retrieved from package __version__.
=> [code health] import style fix

README.md
https://github.com/tensorflow/cloud/issues/110
=> Readme changes for issue #110

RELEASE.md, src/python/tensorflow_cloud/version.py
- Up version to "0.1.7.dev"
- Add merge release notes from release branch
=> Post release update to master

RELEASE.md
Please hold off from reviewing and merging this PR.
=> Lint RELEASE.md

src/python/tensorflow_cloud/core/tests/integration/run_on_script_test.py
These tests are subject to lots of change via suggestions :)
=> Propose added integration tests

src/python/requirements.txt, src/python/tensorflow_cloud/core/tests/testdata/keras_tuner_cifar_example.py, src/python/tensorflow_cloud/core/tests/testdata/mnist_example_using_ctl.py, src/python/tensorflow_cloud/core/tests/testdata/mnist_example_using_fit.ipynb, src/python/tensorflow_cloud/core/tests/testdata/mnist_example_using_fit.py, src/python/tensorflow_cloud/core/tests/testdata/mnist_example_using_fit_no_reqs.py, src/python/tensorflow_cloud/core/tests/testdata/save_and_load.py
=> performance improvement on integration tests

src/python/tensorflow_cloud/core/tests/integration/run_on_script_test.py
- Mock sys.exit mocking to setup
- Fix invalid common machine config
- Remove test that doesn't add coverage
- Remove tpu test as it isn't supported with latest TF version 
- Fix invalid test bucket error
=> Fix integration tests.

src/python/tensorflow_cloud/core/tests/examples/dogs_classification.ipynb
It is breaking rendering on github.
=> Fix broken notebook header

README.md, src/python/tensorflow_cloud/core/README.md, src/python/tensorflow_cloud/core/containerize.py, src/python/tensorflow_cloud/core/tests/integration/run_on_script_test.py, src/python/tensorflow_cloud/core/tests/unit/containerize_test.py
1. Remove the check we have to see if a docker image exists in docker hub.
2. Add error info about wrapping an already wrapped code in dist strat to README.
3. Update core README.
=> Remove docker hub image check

src/python/tensorflow_cloud/tuner/tests/unit/utils_test.py
=> Remove some tests
